pages:
  - Home: index.md

extra:
  logo: _static/logo.jpg
  author:
    github: obestwalter
    twitter: obestwalter
#include_404: True
markdown_extensions:
    - admonition
    - toc:
        permalink: True #¶
repo_url: https://github.com/obestwalter/bindlestiff
site_name: Bindlestiff
strict: True
theme: material
